### PR TITLE
Create haskell-compatibility

### PR DESCRIPTION
**Pull request by ShalokShalom**
Voila ^-^

### CODE REVIEW

**Comment by wallymathieu** [comment]
yay :neckbeard: 👍

**Comment by ShalokShalom** [comment]
Oh, it seems you uploaded the old version. This one here is newer, it contains descriptions for some more operators and all those are capitalized now.

**Comment by gusty** [comment]
Yes, I messed it up. Don't worry will rectify in a while, but I'm trying to find the right format first.

**Comment by ShalokShalom** [comment]
fine fine

I can redo it in an ods and share it as source file, together with a screenshot. 
So, much higher flexibility in terms of highlighting and so on. 

I initially thought the fsharp engine will turn this table into something fancy, not displaying it as is. :)

**Comment by ShalokShalom** [comment]
Fine, thanks a lot. 

I can try to detect this. 

Which engine is in use?

**Pull request merged**
