### PR TITLE
Samples project

### PR DESCRIPTION
**Pull request by wallymathieu**
- This is to compile the samples, should fix part of https://github.com/gusty/FSharpPlus/issues/56
- This should be cleaner than https://github.com/gusty/FSharpPlus/pull/62#issuecomment-354683044 since it's using standard build infrastructure to compile

### CODE REVIEW

**Comment by gusty** [comment]
Works on my machine !

**Comment by wallymathieu** [comment]
```
  <Compile Include="..\FSharpPlus\Samples\*.fsx">
       <Link>Samples\%(FileName)%(Extension)</Link>
   </Compile>
```
😉

**Comment by wallymathieu** [comment]
I agree that this pull request should be squashed, to reduce noise

**Comment by gusty** [comment]
Nice hack !

Anyway don't delete the other branch, I still think it's easier to extend to the docs.

**Comment by wallymathieu** [comment]
I think it's a standard msbuild feature that you can use in a csproj or fsproj ... so probably less hacky than the other solution. I've restored that branch for future reuse.

**Pull request merged**
